### ISSUE TITLE
issue on bowtie index2 is missing

### ISSUE THREAD

**Issue by hongchaoguo** [kundajelab/atac_dnase_pipelines#100]
Hi ,

   I used the command below to run the script in SCG cluster according the link you sent to me. It still tells me the bowtie index2 is missing. Could you have a look?
   bds_scr atac.bds.BDS . atac.bds -q batch --account=joewu -species hg19 -nth 2 -fastq1_1 SRR4011961_1.fastq -fastq1_2 SRR4011961_2.fastq
[SCR_NAME] : atac.bds.BDS.BDS
[HOST] : dper730xd-srcf-d16-01.scg.stanford.edu
[LOG_FILE_NAME] : .
[BDS_PARAM] :  atac.bds -q batch --account=joewu -species hg19 -nth 2 -fastq1_1 SRR4011961_1.fastq -fastq1_2 SRR4011961_2.fastq
Then I opened the “atac.bds.BDS.BDS.log” created and it wrote like this:
Walltime (macs2)                : 23h
Max. memory (macs2)             : 15G
Cap number of peaks (macs2)     : 300K
Extra parameters for macs2 callpeak             :
== callpeak naiver overlap settings
Bedtools intersect -nonamecheck : false
== IDR settings
Append IDR threshold to IDR out_dir     : false
== ATAQC settings

TSS enrichment bed              :

DNase bed for ataqc             :

Promoter bed for ataqc          :

Enhancer bed for ataqc          :

Reg2map for ataqc                       :

Reg2map_bed for ataqc           :

Roadmap metadata for ataqc      :

Max. memory for ATAQC                   : 20G

Walltime for ATAQC                      : 47h

===atac pipeline settings

Type of pipeline                        : atac-seq

Align only                              : false

# reads to subsample replicates (0 if no subsampling)   : 0

# reads to subsample for cross-corr. analysis   : 25000000

No pseudo replicates                    : false

No ATAQC (advanced QC report)           : false

No Cross-corr. analysis                 : false

Use CSEM for alignment                  : false

Smoothing window for MACS2              : 150

DNase Seq                               : false

IDR threshold                           : 0.1

Force to use ENCODE3 parameter set      : false

Force to use ENCODE parameter set       : false

Disable genome browser tracks   : false

p-val thresh. for overlapped peaks      : 0.01

MACS2 p-val thresh. for peaks   : 0.01

MACS2 p-val thresh. for BIGWIGs         : 0.01

Enable IDR on called peaks      : false

Automatically find/trim adapters        : false

== checking atac parameters ...

## 00:00:00.796    **Error (modules/align_bowtie2.bds, line 44, pos 3): Bowtie2 index (-bwt2_idx) doesn't exists! (file: .1.bt2 or .1.bt2l)**

**Comment by leepc12** [comment]
Pipeline supports new SCG now. Replace `-q batch --account=joewu` with `-q joewu` and try again.

=====================
There has been some important updates about SLURM support on Kundaje lab's genomic pipelines (ChIP-Seq and ATAC-Seq) for the new SCG cluster.

0) You don't need to re-install Conda and dependencies

1) Update BigDataScript (IMPORTANT)
cd $HOME
rm -rf .bds/
wget https://github.com/leepc12/BigDataScript/blob/master/distro/bds_Linux.tgz?raw=true -O bds_Linux.tgz
tar zxvf bds_Linux.tgz

2) Update pipeline code
Do git pull on the pipeline git directory.

3) Usage
Add -q YOUR_PI_ACCOUNT_ON_SCG to the pipeline run command line.
The parameter -q is used for sbatch --account on SCG and -p on Sherlock.

-ATAC-Seq: bds atac.bds ... -q YOUR_PI_ACCOUNT_ON_SCG
-ChIP-Seq: bds chipseq.bds ... -q YOUR_PI_ACCOUNT_ON_SCG

Thanks,

Jin
=====================

**Comment by leepc12** [comment]
closing this due to long inactivity.

**Comment by hongchaoguo** [comment]
Ok. Can I contact you at 4:30pm?
Hongchao

2018-04-26 15:59 GMT-07:00 Jin Lee <notifications@github.com>:
