### ISSUE TITLE
Installing genomes from local source. 

### ISSUE THREAD

**Issue by am33567** [kundajelab/atac_dnase_pipelines#107]
Hi, 

I am having trouble running the script 'install_genome_data.sh'. The genome I am using is not online, it is in our lab server. I modify the script to add the genome like this:

elif [ $GENOME == "Vc" ]; then
  REF_FA= '~/genomes/VcPacHM_Vcq_p95_mod.fa'
fi

To run the script I used: 
sh ./install_genome_data.sh Vc ./genome_data/

What I get is:
./install_genome_data.sh: line 137: ~/genomes/VcPacHM_Vcq_p95_mod.fa: No such file or directory

I know the file is there, if I list my file using: ls -lh ~/genomes/VcPacHM_Vcq_p95_mod.fa
-rw-rw-r-- 1 am2622 am2622 406M Apr  3 13:19 /home/am2622/genomes/VcPacHM_Vcq_p95_mod.fa

Any help? 

On the other hand, I have the genomes and their bowtie indexes ready, Is there a way I can indicate the pipeline the path of my files?  I am not using any of the vertebrate genomes in the  install_genome_data.sh' script. 

Thanks,

Anyi

**Comment by leepc12** [comment]
`./install_genome_data.sh` cannot work without internet connection because it uses `wget` to download `REF_FA`. `REF_FA` should be an URL starting with `http`.

Please use it on the computer with internet connection and move output (built genome data) to your computer without internet.

**Comment by am33567** [comment]
Yes, but what if the genomes are not on the internet? Only on my computer?

**Comment by leepc12** [comment]
Okay let replace `wget` with `cp`. Replace line 144 (`wget -c -O $(basename ${REF_FA}) ${REF_FA}`) of `install_genome_data.sh` with the following:
```
cp -f ${REF_FA} .
```
But the installer still needs Conda environment installed on your system.

**Comment by am33567** [comment]
It worked really well.
