### ISSUE TITLE
sbatch: error: unable to open file [account]

### ISSUE THREAD

**Issue by odegoede** [kundajelab/atac_dnase_pipelines#110]
Hi,

I'm trying to run the ATAC-Seq pipeline on SCG, and am hitting an error at the adapter trimming step: 'sbatch: error: Unable to open file smontgom ' (smontgom is my PI/account name).  My command (from an interactive node, in the appropriate working directory) is:
```
bds_scr atac_Fl_unstim $HOME/atac_dnase_pipelines/atac.bds -q smontgom -species mm10 -nth 3 -auto_detect_adapter -pe -fastq1_1 [fastq_R1_file] -fastq1_2 [fastq_R2_file]
```
Attached is the log file.  Any thoughts on why I'm receiving this error would be much appreciated!  Thanks!

[atac_Fl_unstim.BDS.log](https://github.com/kundajelab/atac_dnase_pipelines/files/1975291/atac_Fl_unstim.BDS.log)

**Comment by odegoede** [comment]
Here's what I got for the initial md5sum check:
```
$ md5sum ~/.bds/clusterGeneric/run.pl
c8131abb7299be0a5a54e4b15d07e786  /home/odegoede/.bds/clusterGeneric/run.pl
```
So I updated with the commands you provided and got:
```
$ md5sum ~/.bds/clusterGeneric/run.pl
5618e799e16b02be8c459d91ef5fb66d  /home/odegoede/.bds/clusterGeneric/run.pl
```
This isn't the md5sum that you said, but I've restarted the pipeline and it has progressed into the adapter trimming step with no errors, so things are looking good.  Thanks for your help!

**Comment by leepc12** [comment]
@odegoede sorry, you are right. it should be `5618e799e16b02be8c459d91ef5fb66d`. thanks.
I am closing this.
