### ISSUE TITLE
annotate peaks produced by this pipeline

### ISSUE THREAD

**Issue by llz-hiv** [kundajelab/atac_dnase_pipelines#112]
Hi Jin,

The format of peak files produced by this pipeline seems are bigwig or BB, can I use these files directly for annotation of genomic feature? What I am using for annotation is Chipseeker,  it seems that chipseeker prefer '.bed' as its input format.

Thanks!

**Comment by akundaje** [comment]
The peaks are in narrowPeak and bigbed format. Narrowpeak is an extended
bed format. https://genome.ucsc.edu/FAQ/FAQformat.html#format12

**Comment by llz-hiv** [comment]
It works, thank you!
