### ISSUE TITLE
Is there any difference between Conservative Set and Optimal Set of peaks?

### ISSUE THREAD

**Issue by amirshams84** [kundajelab/atac_dnase_pipelines#117]
I don't see any difference

**Comment by leepc12** [comment]
Those sets don't have to be always different.

How many replicates did you run pipelines with? If it's just one, those two
sets should be identical.

Jin

**Comment by akundaje** [comment]
The optimal set is the maximal set of peaks one can get by comparing true replicates or pseudoreplicates (obtained by pooling reads from true replicates and subsampling equal number of mutually exclusive reads). So some times they can be the same. And they will be the same if there is only one replicate.
