### ISSUE TITLE
messy row labels on "Comparison to Roadmap DNase" plot

### ISSUE THREAD

**Issue by icanwinwyz** [kundajelab/atac_dnase_pipelines#118]
I ran the pipeline smoothly but got the messy row labels on "Comparison to Roadmap DNase" plot from individual sample report. Please find the screen shot attached. Thanks.
<img width="958" alt="screen shot 2018-05-29 at 9 50 00 am" src="https://user-images.githubusercontent.com/2525490/40673228-08bf07c2-6326-11e8-9930-5a27311d2593.png">

**Comment by leepc12** [comment]
Fixed. please update your pipeline and ataqc module
```
$ cd [PIPELINE_GIT_DIR]
$ git pull origin master
$ cd ataqc
$ git pull origin master
```

**Comment by icanwinwyz** [comment]
It took me 3 days to finish the whole pipeline. Should I rerun it again to only fix this plot problem?

**Comment by leepc12** [comment]
you can delete odl ATAQC reports with the following command:
```
$ cd [YOUR_OUTPUT_DIR]
$ find -name *_qc.html -delete
```
This command will recursively DELETE all `*_qc.html` files on your output directory.

Delete all ATAQC HTML report and simply run the same command line then pipeline will automatically resume from ATAQC step.
