### ISSUE TITLE
stops at idr2

### ISSUE THREAD

**Issue by ahorn720** [kundajelab/atac_dnase_pipelines#119]
Hello,
I have 3 samples im trying to run and although one of them runs completely, for some reason, the next 2 samples both stop at the idr2 step. Any suggestions would be very helpful.

Thank you,
Aaron

[NBM_55stderror.txt](https://github.com/kundajelab/atac_dnase_pipelines/files/2055707/NBM_55stderror.txt)
[NBM_55stdout.txt](https://github.com/kundajelab/atac_dnase_pipelines/files/2055708/NBM_55stdout.txt)

**Comment by ahorn720** [comment]
I've repeated the run a few times now and I keep getting the same errors. Any suggestions?

**Comment by leepc12** [comment]
Run the following for more info:
`$ zcat /labs/ccurtis2/aaron/data_miseq_omniATACseq_NBM15-55-40/Files/Analysis/Fastqs/NBM_55_Peaks_pipeline_out/peak/macs2/idr/pseudo_reps/rep1/NBM_55_rep1-pr.IDR0.1.13-col.bed.gz | wc -l`

It looks like no peak passed the IDR threshold?

**Comment by ahorn720** [comment]
yep... i returns `0`. Ok thank you for your time and the suggestion. I'll try raising the threshold and just removing that step possibly.
