### ISSUE TITLE
queue option on Sherlock

### ISSUE THREAD

**Issue by timydaley** [kundajelab/atac_dnase_pipelines#120]
Hi, 
I'm having issues running the pipeline on a partition in Sherlock, rather than the main queue.  The commands are below.
TITLE=MEF+Ascl1_13d_B1_rep1;SPECIES=mm10;
FASTQ1_1=/scratch/PI/whwong/tdaley/YanxiaRNAseq/Public/WapinksiAscl1Induction/ATACseq/MEF+Ascl1_13d_B1_rep1_1.fastq.gz
FASTQ1_2=/scratch/PI/whwong/tdaley/YanxiaRNAseq/Public/WapinksiAscl1Induction/ATACseq/MEF+Ascl1_13d_B1_rep1_2.fastq.gz
WORK=/scratch/PI/whwong/tdaley/YanxiaRNAseq/Public/WapinksiAscl1Induction/ATACseq/$TITLE; 
mkdir -p $WORK; 
cd $WORK
bds_scr $TITLE /scratch/PI/whwong/tdaley/programs/atac_dnase_pipelines/atac.bds -species $SPECIES -nth 4 -fastq1_1 $FASTQ1_1 -fastq1_2 $FASTQ1_2 -system slurm -q_for_slurm_account -q whwong -auto_detect_adapter --account whwong -align

This results in the error
sbatch: error: Unable to open file whwong

changing the command to 
bds_scr $TITLE /scratch/PI/whwong/tdaley/programs/atac_dnase_pipelines/atac.bds -species $SPECIES -nth 4 -fastq1_1 $FASTQ1_1 -fastq1_2 $FASTQ1_2 -system slurm -q_for_slurm_account  whwong -auto_detect_adapter -align
results in everything being submitted to the normal queue.

Thank you for your time and help.

**Comment by leepc12** [comment]
Update your BDS
https://github.com/kundajelab/atac_dnase_pipelines#bigdatascript

**Comment by timydaley** [comment]
I had followed these directions the first time, but I still updated and it's still submitting jobs through the normal queue.

**Comment by timydaley** [comment]
bds --version
Picked up _JAVA_OPTIONS: -Xms256M -Xmx728M -XX:ParallelGCThreads=1
Error: Unknown command line option --version
Bds 0.99999e (build 2016-08-26 06:34), by Pablo Cingolani

**Comment by leepc12** [comment]
Please post output of the following.
```
cat ~/.bds/clusterGeneric/run.pl
```

**Comment by timydaley** [comment]
$ cat ~/.bds/clusterGeneric/run.pl
#!/usr/bin/perl

use POSIX;

die "Error: Missing arguments.\nUsage: run.pl timeout cpus mem queue saveStdout saveStderr cmd arg1 ... argN\n" if $#ARGV < 6 ;

$timeout = shift @ARGV;
$cpus = shift @ARGV;
$mem = shift @ARGV;
$queue = shift @ARGV;
$saveStdout = shift @ARGV;
$saveStderr = shift @ARGV;
$cmd = join(' ', @ARGV);

$qsub = "sbatch --export=ALL ";
$qsub .= "-n 1 --ntasks-per-node=1 --cpus-per-task=$cpus " if( $cpus > 0 );
if( $mem > 0 ) {
	$mem = ceil($mem/1000000); # MB
	if ( $cpu > 0 ) {
		$mem = $mem*$cpu
	}
	$qsub .= "--mem $mem ";
}
if( $timeout > 0 ) {
	$timeout = ceil($timeout/60); # minute
	$qsub .= "-t $timeout ";
}
if ( $queue ne "" ) {
        $qsub .= " $queue "
}

$pid = open QSUB, " | $qsub";
die "Cannot run command '$qsub'\n" if ! kill(0, $pid); # Check that process exists
print QSUB "#!/bin/sh \n";	# SLURM sbatch needs this shebang...
print QSUB "$cmd\n";		# Send cluster's task via qsub's STDIN
close QSUB;

exit(0);


Thank you again for your help.

**Comment by leepc12** [comment]
Remove `--account whwong` and try again.

**Comment by timydaley** [comment]
Command is now
bds_scr $TITLE /scratch/PI/whwong/tdaley/programs/atac_dnase_pipelines/atac.bds -species $SPECIES -nth 4 -fastq1_1 $FASTQ1_1 -fastq1_2 $FASTQ1_2 -system slurm -q_for_slurm_account -queue whwong -auto_detect_adapter -align

same error, see below

00:00:15.007	Waiting for all tasks to finish.
00:00:15.007	Wait: Waiting for task to finish: atac.bds.20180601_122100_921_parallel_28/task.align_trim_adapter.trim_adapters_PE_rep1.line_134.id_10, state: SCHEDULED
00:00:15.009	ExecutionerClusterGeneric 'ClusterGeneric[29]': Started running
00:00:15.016	ExecutionerClusterGeneric 'ClusterGeneric[29]': Task selected 'atac.bds.20180601_122100_921_parallel_28/task.align_trim_adapter.trim_adapters_PE_rep1.line_134.id_10' on host 'localhost'
sbatch: error: Unable to open file whwong
Task failed:
	Program & line     : '/scratch/PI/whwong/tdaley/programs/atac_dnase_pipelines/modules/align_trim_adapter.bds', line 134
	Task Name          : 'trim_adapters_PE rep1'
	Task ID            : 'atac.bds.20180601_122100_921_parallel_28/task.align_trim_adapter.trim_adapters_PE_rep1.line_134.id_10'
	Task PID           : 'null'
	Task hint          : 'cutadapt -m 5 -e 0.10 -a CTGTCTCTTATA -A CTGTCTCTTATA -o /scratch/PI/whwong/tdaley/YanxiaRNAseq/Public/WapinksiAscl1Induction/ATACseq/MEF+Ascl1_13d_B1_rep1/out/align/rep1/MEF+Ascl1_13d_B1_rep1_1.trim.fastq -p /scratch/PI/whwong/tdaley/YanxiaRNAseq/Public/WapinksiAscl1Induction/ATACseq/MEF+Ascl1_13d_'
	Task resources     : 'cpus: -1	mem: 12.0 GB	timeout: 82800	wall-timeout: 8640000'
	State              : 'START_FAILED'
	Dependency state   : 'ERROR'
	Retries available  : '1'
	Input files        : '[/scratch/PI/whwong/tdaley/YanxiaRNAseq/Public/WapinksiAscl1Induction/ATACseq/MEF+Ascl1_13d_B1_rep1_1.fastq.gz, /scratch/PI/whwong/tdaley/YanxiaRNAseq/Public/WapinksiAscl1Induction/ATACseq/MEF+Ascl1_13d_B1_rep1_2.fastq.gz]'
	Output files       : '[/scratch/PI/whwong/tdaley/YanxiaRNAseq/Public/WapinksiAscl1Induction/ATACseq/MEF+Ascl1_13d_B1_rep1/out/align/rep1/MEF+Ascl1_13d_B1_rep1_1.trim.fastq.gz, /scratch/PI/whwong/tdaley/YanxiaRNAseq/Public/WapinksiAscl1Induction/ATACseq/MEF+Ascl1_13d_B1_rep1/out/align/rep1/MEF+Ascl1_13d_B1_rep1_2.trim.fastq.gz]'
	Script file        : '/scratch/PI/whwong/tdaley/YanxiaRNAseq/Public/WapinksiAscl1Induction/ATACseq/MEF+Ascl1_13d_B1_rep1/atac.bds.20180601_122100_921_parallel_28/task.align_trim_adapter.trim_adapters_PE_rep1.line_134.id_10.sh'
	Error message      : 'sbatch: error: Unable to open file whwong
'
	Exit status        : '1'
	Program            : 
		
		# SYS command. line 136
		
		 if [[ -f $(which conda) && $(conda env list | grep bds_atac | wc -l) != "0" ]]; then source activate bds_atac; sleep 5; fi;  export PATH=/scratch/PI/whwong/tdaley/programs/atac_dnase_pipelines/.:/scratch/PI/whwong/tdaley/programs/atac_dnase_pipelines/modules:/scratch/PI/whwong/tdaley/programs/atac_dnase_pipelines/utils:${PATH}:/bin:/usr/bin:/usr/local/bin:${HOME}/.bds; set -o pipefail; STARTTIME=$(date +%s)
		
		# SYS command. line 138
		
		 cutadapt -m 5 -e 0.10 -a CTGTCTCTTATA -A CTGTCTCTTATA -o /scratch/PI/whwong/tdaley/YanxiaRNAseq/Public/WapinksiAscl1Induction/ATACseq/MEF+Ascl1_13d_B1_rep1/out/align/rep1/MEF+Ascl1_13d_B1_rep1_1.trim.fastq -p /scratch/PI/whwong/tdaley/YanxiaRNAseq/Public/WapinksiAscl1Induction/ATACseq/MEF+Ascl1_13d_B1_rep1/out/align/rep1/MEF+Ascl1_13d_B1_rep1_2.trim.fastq /scratch/PI/whwong/tdaley/YanxiaRNAseq/Public/WapinksiAscl1Induction/ATACseq/MEF+Ascl1_13d_B1_rep1_1.fastq.gz /scratch/PI/whwong/tdaley/YanxiaRNAseq/Public/WapinksiAscl1Induction/ATACseq/MEF+Ascl1_13d_B1_rep1_2.fastq.gz
		
		# SYS command. line 140
		
		 gzip -f /scratch/PI/whwong/tdaley/YanxiaRNAseq/Public/WapinksiAscl1Induction/ATACseq/MEF+Ascl1_13d_B1_rep1/out/align/rep1/MEF+Ascl1_13d_B1_rep1_1.trim.fastq
		
		# SYS command. line 141
		
		 gzip -f /scratch/PI/whwong/tdaley/YanxiaRNAseq/Public/WapinksiAscl1Induction/ATACseq/MEF+Ascl1_13d_B1_rep1/out/align/rep1/MEF+Ascl1_13d_B1_rep1_2.trim.fastq
		
		# SYS command. line 143
		
		 TASKTIME=$[$(date +%s)-${STARTTIME}]; if [ ${TASKTIME} -lt 60 ]; then echo "Waiting for $[60-${TASKTIME}] seconds."; sleep $[60-${TASKTIME}]; sleep 30; fi

00:00:15.273	Wait: Task 'atac.bds.20180601_122100_921_parallel_28/task.align_trim_adapter.trim_adapters_PE_rep1.line_134.id_10' finished.
Fatal error: /scratch/PI/whwong/tdaley/programs/atac_dnase_pipelines/atac.bds, line 767, pos 3. Task/s failed.

Creating checkpoint file: Config or command line option disabled checkpoint file creation, nothing done.
00:00:15.454	Parallel 'atac.bds.20180601_122100_921_parallel_28' finished, exit value: 1, tasks executed: 1, tasks failed: 1, tasks failed names: trim_adapters_PE rep1.
Fatal error: /scratch/PI/whwong/tdaley/programs/atac_dnase_pipelines/atac.bds, line 426, pos 2. Task/s failed.
atac.bds, line 82 :	main()
atac.bds, line 85 :	void main() { // atac pipeline starts here
atac.bds, line 95 :		do_align()
atac.bds, line 394 :	void do_align() {
atac.bds, line 426 :		wait

Creating checkpoint file: Config or command line option disabled checkpoint file creation, nothing done.
00:00:15.827	Writing report file 'atac.bds.20180601_122100_921.report.html'
00:00:15.923	Program 'atac.bds.20180601_122100_921' finished, exit value: 1, tasks executed: 1, tasks failed: 1, tasks failed names: trim_adapters_PE rep1.
00:00:15.924	Finished. Exit code: 1
00:00:15.924	ExecutionerClusterGeneric 'ClusterGeneric[29]': Killed

**Comment by leepc12** [comment]
What is your pipeline version? You can check latest commit for the pipeline
in the top of the log.

Can you update the pipeline and try again?
```
$ cd [PIPELINE_GIT_DIR]
$ git pull
$ cd ataqc
$ git pull origin master
```

**Comment by timydaley** [comment]
Excellent.  That seemed worked.  I apologize for not doing this from the start.  Thank you so much for your help.
