### ISSUE TITLE
shuf: read error: Cannot allocate memory at spr_tag_PE step

### ISSUE THREAD

**Issue by chesi** [kundajelab/atac_dnase_pipelines#121]
Hi,
how do I increase the memory allocation for this step: spr_tag_PE?
The default 12G is not enough. This step is not listed in the atac.config file.
I attach the bds.log file.
Thanks!
[bds.log](https://github.com/kundajelab/atac_dnase_pipelines/files/2068571/bds.log)

**Comment by chesi** [comment]
Thanks!

Alessandra

**Comment by chesi** [comment]
Thanks!

Also, is there a rule of thumb to estimate the memory requirements for the atacqc step?

My jobs keep dying because they do not have enough memory, and I am increasing allocation in steps, but it takes a long time to guess the right amount of memory.

Thanks,

A.

**Comment by leepc12** [comment]
Sorry, it's hard to estimate. Please start with large enough memory...
