### ISSUE TITLE
which files created by this pipeline can be used for homer to find motifs?

### ISSUE THREAD

**Issue by llz-hiv** [kundajelab/atac_dnase_pipelines#131]
There are 3 basic ways to run HOMER - with FASTA files, with Gene Identifiers, or from Genomic Positions. Can narrow peak files be directly used for Homer to find motifs?

Thanks

**Comment by akundaje** [comment]
NarrowPeak files are just BED files with more columns for additional information. If you extract the first 3 columns from the narrowPeak file, that will provide you the peak boundary coordinates. You should be able to feed that in any motif discovery method in whatever format they expect.
