### ISSUE TITLE
Broken link in the README

### ISSUE THREAD

**Issue by k3yavi** [kundajelab/atac_dnase_pipelines#148]
Hi,

Thanks for writing the great pipeline !
I am curious about the atac-seq pipeline and wondering were you suppose to refer to [this](https://github.com/ENCODE-DCC/atac-seq-pipeline) repo in the README ? The current [link](https://github.com/kundajelab/atac-seq-pipeline) seems to be broken.

**Comment by akundaje** [comment]
Please use this official version of the pipeline https://github.com/ENCODE-DCC/atac-seq-pipeline . The one on this site is a fork and is not actively updated.
