### ISSUE TITLE
Error Message: "No such file or directory found: 'java': 'java'"

### ISSUE THREAD

**Issue by astephen333** [kundajelab/atac_dnase_pipelines#149]
Tried to run the pipeline on the test case in the Github and the above error message popped up. I also noticed that the previous analysis always says skipped due to md5_match, rather than the usual started. done. message. Attached is a picture of my terminal.

This is on a Linux cluster that has slurm with v2.1.3.

<img width="1072" alt="Screenshot 2022-05-23 at 2 38 47 PM" src="https://user-images.githubusercontent.com/65789685/169885167-e327225f-93c7-4fdc-a113-8f902a2ad378.png">

**Comment by leepc12** [comment]
It looks like that you don't have `java` on your system
```bash
$ java -version
```
This pipeline is no longer maintained. Please use https://github.com/ENCODE-DCC/atac-seq-pipeline instead.

**Comment by astephen333** [comment]
So sorry, this issue was for the atac-seq-pipeline from ENCODE-DCC. I'll look into your comment and repost if necessary.
