### ISSUE TITLE
Remove Picard from the pipeline

### ISSUE THREAD

**Issue by chrisprobert** [kundajelab/atac_dnase_pipelines#18]
Currently, we only use Picard for the MarkDuplicates step in `_dedup_bam`, `_dedup_bam_pe`, and in `ataqc` to check for mito duplicates. We should remove Picard from the pipeline and replace it with a more efficient, non-java duplicate finder that can handle reads present from multiple lanes in the same bam read group. This will significantly improve user experience and reliability for users who have lane-merged demultiplexed fastqs.

cc: @nboley @vervacity

**Comment by akundaje** [comment]
Chris. Picard is by-far the accepted standard for dup filtering. Samtools
is buggy and I dont know of any other. But if we find one that is
maintained and reproduces PICARD's output that would be fine.

**Comment by chrisprobert** [comment]
@akundaje: Agreed Picard is the current standard for dup filtering.

In terms of technical debt, it would be great to remove java from the pipeline (aside from BDS). In terms of functionality and use case, we need to do a better job for users who have lane-merged fastqs -- currently Picard crashes when a user runs the pipeline with a lane-merged fastq.

Two other options we could look at:
sambamba: https://github.com/lomereiter/sambamba
samblaster: https://github.com/GregoryFaust/samblaster

**Comment by akundaje** [comment]
Definitely. I would vote to remove java from the world :)

**Comment by chrisprobert** [comment]
After benchmarking, I've found that sambamba markdups (https://github.com/lomereiter/sambamba) has the same behavior across several bam files as picard MarkDuplicates. Sambamba does not crash on lane-merged fastqs like Picard does.

I've created a branch of [bds_atac](https://github.com/kundajelab/bds_atac/tree/sambamba) and chipseq (https://github.com/kundajelab/chipseq/tree/sambamba) that provides preliminary support for optionally using sambamba for de-duping bams.

**Comment by akundaje** [comment]
Thats great. Chris - Can you work with Jin on revising the google doc that
has the pipeline specifications (exact commands) to replace the PICARD
commands with the sambamba ones.

**Comment by chrisprobert** [comment]
Yep, will do once exact commands and options are sorted.

Currently there are differences in the output metrics that I need to fix before we can merge: sambamba reports `total paired seqs marked dup` (where PE reads with both ends marked dup are counted twice), whereas picard reports `total pairs marked dup` (where a PE read is only counted once if one or both reads are marked dup). I will write a post-processing step for sambamba to count the total number of pairs where one or both reads are marked dup, so the metrics we report are consistent with picard.
