### ISSUE TITLE
Missing config file entry 'sge.pe' 

### ISSUE THREAD

**Issue by boxiangliu** [kundajelab/atac_dnase_pipelines#27]
Hi Jin Wook,

I am a PhD student in Montgomery lab. I am using your pipeline on durga. When running the pipeline, I got the following error: 

`Fatal error: /srv/persistent/bliu2/tools/atac_dnase_pipelines/modules/align_trim_adapter.bds, line 129, pos 9. Missing config file entry 'sge.pe'`

I looked into the git repo and was not able to find an example of `sge.pe`. Seeing it maybe related to Sun Grid Engine, I tried to work around by adding the option `-use_system local`. However, I still get the same error. 

Could you suggest a way to circumvent this error?

**Comment by leepc12** [comment]
I recently removed mitra and durga from the server list controlled by SGE. There was some misconfigured settings for mitra and durga after that.

Fixed in 48f75b88761da81d7e5cc6f840748eb63f659bea

**Comment by boxiangliu** [comment]
Cool. I ended up changing the kundaje.env file from sge to local and that temporarily fixed the problem. Thanks! 

By the way, I want to thank you for making such a useful pipeline available.
