### ISSUE TITLE
problem installing genome

### ISSUE THREAD

**Issue by PocketChangeJ** [kundajelab/atac_dnase_pipelines#29]
Hi, I'm encountering errors running install_genome_data.sh - seems problem with index building (see below). Here I was setting up mm10, but getting same problem with other genomes too. Thanks!

Downloading files...
--2016-12-01 19:25:18--  ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_mouse/release_M10/GRCm38.p4.genome.fa.gz
           => â€œ.listingâ€
Resolving ftp.sanger.ac.uk... 193.62.203.17
Connecting to ftp.sanger.ac.uk|193.62.203.17|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/gencode/Gencode_mouse/release_M10 ... done.
==> PASV ... done.    ==> LIST ... done.

    [ <=>                                                                                       ] 3,784       --.-K/s   in 0s      

2016-12-01 19:25:20 (414 MB/s) - â€œ.listingâ€ saved [3784]

Removed â€œ.listingâ€.
--2016-12-01 19:25:20--  ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_mouse/release_M10/GRCm38.p4.genome.fa.gz
           => â€œGRCm38.p4.genome.fa.gzâ€
==> CWD not required.
==> PASV ... done.    ==> RETR GRCm38.p4.genome.fa.gz ... done.
Length: 776171698 (740M)

100%[==========================================================================================>] 776,171,698 19.2M/s   in 79s     

2016-12-01 19:26:43 (9.35 MB/s) - â€œGRCm38.p4.genome.fa.gzâ€ saved [776171698]

--2016-12-01 19:26:43--  http://mitra.stanford.edu/kundaje/genome_data/mm10/mm10.blacklist.bed.gz
Resolving mitra.stanford.edu... 171.65.76.236
Connecting to mitra.stanford.edu|171.65.76.236|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1263 (1.2K) [application/x-gzip]
Saving to: â€œmm10.blacklist.bed.gzâ€

100%[==========================================================================================>] 1,263       --.-K/s   in 0s      

2016-12-01 19:26:43 (203 MB/s) - â€œmm10.blacklist.bed.gzâ€ saved [1263/1263]

Extracting/processing data files...
Building bowtie2 index...
Settings:
  Output files: "GRCm38.p4.genome.fa.*.bt2"
  Line rate: 6 (line is 64 bytes)
  Lines per side: 1 (side is 64 bytes)
  Offset rate: 4 (one in 16)
  FTable chars: 10
  Strings: unpacked
  Max bucket size: default
  Max bucket size, sqrt multiplier: default
  Max bucket size, len divisor: 4
  Difference-cover sample period: 1024
  Endianness: little
  Actual local endianness: little
  Sanity checking: disabled
  Assertions: disabled
  Random seed: 0
  Sizeofs: void*:8, int:4, long:8, size_t:8
Input files DNA, FASTA:
  GRCm38.p4.genome.fa
Building a SMALL index
Reading reference sizes
  Time reading reference sizes: 00:00:39
Calculating joined length
Writing header
Reserving space for joined string
Joining reference sequences
  Time to join reference sequences: 00:00:24
bmax according to bmaxDivN setting: 665501219
Using parameters --bmax 499125915 --dcv 1024
  Doing ahead-of-time memory usage test
./install_genome_data.sh: line 187: 29304 Killed                  bowtie2-build ${REF_FA_PREFIX} ${REF_FA_PREFIX}

**Comment by leepc12** [comment]
Your computer (or cluster) killed the index-building job (possibly due to resource limit).
Did you run the installer on a cluster login node (where resource usage is limited)?

**Comment by PocketChangeJ** [comment]
I see.
Yes, I tried on sherlock using sdev, and im getting same error while trying to run this on corn as well (though didn't have any problems running earlier versions of the pipeline ther).. does this mean I should try lowering the requirements while running the index job? Thank you.

**Comment by leepc12** [comment]
Building index takes more than an hour and a lot of memory. Can you try sdev with additional resource settings (like 3 hours of walltime and >10GB of memory)?

**Comment by PocketChangeJ** [comment]
I tried with sdev 2h and 8GB just now - that's max I'm allowed on sherlock, but I've ended up with the same error.. I could potentially link things to the pre-existing bowtie2 index, is that correct? Thanks again.

**Comment by leepc12** [comment]
Please replace `BUILD_BWT2_IDX=1` with `BUILD_BWT2_IDX=0` in `./install_genome_data.sh` and then try again. After installation, add your pre-existing bowtie2 index to the species file. See the following example.
```
[YOUR_GENOME_NAME]
...
bwt2_idx        = /mnt/data/bds_pipeline_genome_data/hg38/bowtie2_index/GRCh38.p3.genome.fa
...
```
Your species file will be located on the directory you installed the genome data.

**Comment by PocketChangeJ** [comment]
Hi there, thank you, I'll try it this way.

Re. failed indexing - I've started sdev and then run the command interactively, and it seems to me the `sacct -j` does not exactly show me what i need... I'm new to Sherlock and I'm not sure yet how to check why the indexing failed, but I'll be very much interested in figuring this out.
Thank you once again

**Comment by leepc12** [comment]
You can try `sacct -j 29304`.

**Comment by PocketChangeJ** [comment]
Ah, I see what you mean.
I tried that just now after tho after attempting to run the /install_genome_data.sh again - in the end I got this time:
`   Doing ahead-of-time memory usage test
./install_genome_data.sh: line 187:  5554 Killed                  bowtie2-build ${REF_FA_PREFIX} ${REF_FA_PREFIX}`
then tried `sacct -j 5554`, but this returns just an empty table:
`       JobID    JobName  Partition    Account  AllocCPUS      State ExitCode 
------------ ---------- ---------- ---------- ---------- ---------- -------- `

Do you think that indeed the resources available while using dev are not sufficient?
Thanks again.
