### ISSUE TITLE
preseq dependency error

### ISSUE THREAD

**Issue by rfarouni** [kundajelab/atac_dnase_pipelines#30]
When installing the pipeline, I get the following error:
```
-bash-4.1$ ./install_dependencies.sh
Fetching package metadata ...........
Solving package specifications: .


PackageNotFoundError: Package not found: '' Dependency missing in current linux-64 channels: 
  - preseq ==2.0.2 -> gsl 1.16*
```
If I install *gsl*  manually I get the 2.2.1-0 version instead

```
conda install gsl

The following NEW packages will be INSTALLED:

    gsl:    2.2.1-0
    libgcc: 5.2.0-0

```

**Comment by ivargr** [comment]
I faced the same problem, and I think it can be solved by doing:

conda install -c bioconda preseq=2.0.2
conda install -c bioconda gsl=1.8

**Comment by rfarouni** [comment]
These didn't work. I am working on the cluster node, and the only thing that worked is 

```
conda install preseq --channel bioconda

```

**Comment by leepc12** [comment]
I added the channel `asmeurer` for gsl 1.16.
