### ISSUE TITLE
issue with linking packages ?

### ISSUE THREAD

**Issue by PocketChangeJ** [kundajelab/atac_dnase_pipelines#32]
```
Linking packages ...
/home/Programs/miniconda3/envs/bds_atac/bin/.openssl-post-link.sh: line 7: 26079 Segmentation fault      $PREFIX/bin/.openssl-libcrypto-fix $PREFIX


LinkError: Link error: Error: post-link failed for: openssl-1.0.2k-0

```

Thanks!

**Comment by leepc12** [comment]
https://github.com/conda/conda/issues/1260

I removed glibc from the installer. please git pull.

please uninstall_dependencies.sh and then install_dependencies.sh again.

**Comment by PocketChangeJ** [comment]
Ah, yes. Thank you!

**Comment by leepc12** [comment]
Please let me know if it works.
Thanks,

**Comment by idalundback** [comment]
@leepc12 

Hello, 

I have just tried to install Jupyter by conda and got a very similar error message as above. 

I am completely new to this and was googling around for someone experiencing a similar problem. 

This is the output i get:

jupyter-1.0.0- 100% |################################| Time: 0:00:00   3.21 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
/macqiime/anaconda/bin/.openssl-post-link.sh: line 7:   477 Segmentation fault: 11  "$PREFIX"/bin/.openssl-libcrypto-fix "$PREFIX"
Error: Error: post-link failed for: openssl-1.0.2l-0 

i saw from your previous message that you recommended to : uninstall_dependencies.sh and then install_dependencies.sh again.

do i simply just type this into the terminal? Super sorry but yes, all new to this and completely lost! 

Thank you! 

Ida

**Comment by billtubbs** [comment]
I am also having the same error installing Anaconda on my old MacBook (OS X 10.7.5).

This is the output when I install using the command-line installer:

installing: anaconda-4.4.0-np112py27_0 ...
installing: conda-4.3.21-py27_0 ...
installing: conda-env-2.6.0-0 ...
Python 2.7.13 :: Continuum Analytics, Inc.
creating default environment...
/Users/billtubbs/anaconda2/bin/.openssl-post-link.sh: line 7: 4797 Segmentation fault: 11 "$PREFIX"/bin/.openssl-libcrypto-fix "$PREFIX"
Error: post-link failed for: openssl-1.0.2l-0

**Comment by linwoodc3** [comment]
@billtubbs, I got around the problem by doing this:

`conda install openssl=1.0.2d`; once I got that installed, I could do everything on my macbook with 10.7.5
