### ISSUE TITLE
ERROR [ file 'atac.bds', line 1304 ] :	Function parse_align_log_to_html(string,string[],string[],string[]) cannot be resolved

### ISSUE THREAD

**Issue by jet456** [kundajelab/atac_dnase_pipelines#34]
Hi,

I am trying to run the atac dnase pipeline and am getting this error.

bash-4.1$ bds atac.bds -species hg19 -nth 4 -se -bam1 file1.bam -bam2 file2.bam

Picked up _JAVA_OPTIONS: -Xms256M -Xmx728M -XX:ParallelGCThreads=1

Compiler messages:
ERROR [ file 'atac.bds', line 1304 ] :	Function parse_align_log_to_html(string,string[],string[],string[]) cannot be resolved
ERROR [ file 'atac.bds', line 1305 ] :	Function parse_dup_to_html(string,string[],string[],string[]) cannot be resolved
ERROR [ file 'atac.bds', line 1306 ] :	Function parse_flagstat_to_html(string,string[],string[],string[],bool) cannot be resolved
ERROR [ file 'atac.bds', line 1307 ] :	Function parse_pbc_to_html(string,string[],string[],string[]) cannot be resolved
ERROR [ file 'atac.bds', line 1308 ] :	Function parse_xcor_to_html(string,string[],string[],string[],string[]) cannot be resolved
ERROR [ file 'atac.bds', line 1312 ] :	Function parse_idr_to_html(string,string) cannot be resolved
ERROR [ file 'atac.bds', line 1327 ] :	Function parse_ataqc_txt(string,string[],string[]) cannot be resolved

Compiler messages:
ERROR [ file 'atac.bds', line 1304 ] :	Function parse_align_log_to_html(string,string[],string[],string[]) cannot be resolved
ERROR [ file 'atac.bds', line 1305 ] :	Function parse_dup_to_html(string,string[],string[],string[]) cannot be resolved
ERROR [ file 'atac.bds', line 1306 ] :	Function parse_flagstat_to_html(string,string[],string[],string[],bool) cannot be resolved
ERROR [ file 'atac.bds', line 1307 ] :	Function parse_pbc_to_html(string,string[],string[],string[]) cannot be resolved
ERROR [ file 'atac.bds', line 1308 ] :	Function parse_xcor_to_html(string,string[],string[],string[],string[]) cannot be resolved
ERROR [ file 'atac.bds', line 1312 ] :	Function parse_idr_to_html(string,string) cannot be resolved
ERROR [ file 'atac.bds', line 1327 ] :	Function parse_ataqc_txt(string,string[],string[]) cannot be resolved

I downloaded and extracted the pipeline, pointed it with PATH and LD_LIBRARY_PATH to Miniconda3 and Java, ran ./install_dependencies.sh, ran ./install_genome_data.sh for hg19, all of those were successful. When I go to run the pipeline I get this error. Have you seen this before?

Thank you!

**Comment by leepc12** [comment]
There was a major update for the report generation and those compilation errors seem to come from it. Please git pull the code and try again with `bds /path_to_code/atac.bds` to check any complication errors.

**Comment by jet456** [comment]
Done! The error is fixed. Thank you!
