### ISSUE TITLE
Low TSS Enrichment Scores

### ISSUE THREAD

**Issue by rleylek** [kundajelab/atac_dnase_pipelines#35]
The last few samples I analyzed had unusually low TSS Enrichment Scores (compared to other samples I ran last night and my collaborator's analysis of the same samples). I saw the latest updates today had to do with the TSS_enrich plots - could that affect it? Thanks!

**Comment by vervacity** [comment]
Hi - if you are seeing a difference between updates (as in, the TSS enrichment scores before the update were fine and then afterward were lower) then yes, that is likely an effect of the annotation update.

**Comment by rleylek** [comment]
Hi, yes exactly.

Here's analysis I ran before the last update (2/8/17):
![screen shot 2017-02-13 at 5 10 42 pm](https://cloud.githubusercontent.com/assets/25571258/22910540/7c25c0ea-f20f-11e6-80bf-2fda31bd4b4b.png)


Here's the same sample, re-run today:
![screen shot 2017-02-13 at 5 10 08 pm](https://cloud.githubusercontent.com/assets/25571258/22910536/7709a32e-f20f-11e6-9dbc-43e3fe181d1e.png)

The first matches up with my collaborator's analysis - great quality. The second would indicate that it (and all of my other samples) need to be thrown out! For now, I'm going to continue with downstream analysis and assume it's a problem with calculating or displaying the TSS enrichment score, but just wanted to point it out.

Thanks!!
-Becky

**Comment by vervacity** [comment]
Hi Becky,

Just checking in on this. The annotations have significantly stabilized, so if you'd like to run the QC again you should get very similar results to your first result. (If you do re-run, make sure to get the latest code as well as the latest download of genome annotations) Let us know if you run into any problems with it.

Cheers,
Daniel

**Comment by rleylek** [comment]
Hi Daniel,

Thanks for the update! I’ll be running all of my samples through the pipeline again once I get my next set of sequencing back, hopfully next week. I’ll let you know if it looks right!

Best,
-Becky
--
Rebecca Leylek
Immunology Graduate Student
Idoyaga Lab




On May 9, 2017, at 3:17 PM, Daniel Kim <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Becky,

Just checking in on this. The annotations have significantly stabilized, so if you'd like to run the QC again you should get very similar results to your first result. (If you do re-run, make sure to get the latest code as well as the latest download of genome annotations) Let us know if you run into any problems with it.

Cheers,
Daniel
