### ISSUE TITLE
no idr?

### ISSUE THREAD

**Issue by PocketChangeJ** [kundajelab/atac_dnase_pipelines#38]
Hello again,
I'm running your pipeline with mm10 - it seems like the runs stop after peak calling with macs2, and idr never kicks in? 
I didn't include the "no_idr" option.
Another note - all the intermediate files remain, no errors reported.
Thanks!

**Comment by leepc12** [comment]
Please post the error log (STDOUT) or an HTML report here. I need them for debugging.
Did you get [TITLE]_report.html in your out_dir (./out by default)?

**Comment by PocketChangeJ** [comment]
hi,
yes. i'm attaching both. 
thanks!

[atac.bds.20170226_124617_280.report.html.zip](https://github.com/kundajelab/atac_dnase_pipelines/files/804622/atac.bds.20170226_124617_280.report.html.zip)
[rtTA_NTC.BDS.log.zip](https://github.com/kundajelab/atac_dnase_pipelines/files/804623/rtTA_NTC.BDS.log.zip)

**Comment by leepc12** [comment]
Is the attached report the latest one? BDS generates such HTML report per run. Please look at HTML's filename and check timestamp of it to choose the latest one. MACS2 doesn't show up in the attached HTML report.

Your log says MACS2 peak calling is in progress but the last timestamp on the log is "INFO  @ Sun, 26 Feb 2017 23:27:10". Please post the latest log here.

Did you get peaks on [out_dir]/peaks/macs2?
Did you get [TITLE]_report.html in your out_dir (./out by default)?

**Comment by PocketChangeJ** [comment]
Hi,
yup its the latest one... I've noticed macs doesn't show too - I do get some peak files in macs2 directory - not all files are generated though: 
For rep1 I've got:
*.broadPeak, *.gappedPeak, *.narrowPeak, *.pval0.1.broadPeak, pval0.1gappedPeak, and pval0.1.barrowPeak
rep2 folder has only first 3 files. Pseudo_reps is only just partial (for rep1), nothing else was generated.

There is no html report in my out_dir.
But there is still a folder with all the task.*.sh, and *.stderr, *.stdout and *.exitCode files - the one with the last timestamp is id_57.sh... but there is no recorded error that I can see (not sure I'm looking at this right though).

I tried running this sample twice yesterday- both times it got stuck this way.. Not sure what can I try - I'm relatively new to all this - could something be wrong with my installation etc? 
Thanks again.

**Comment by PocketChangeJ** [comment]
Ugh, ok. I've restarted my session and re-installed the dependencies again. Things are running fine and I'm past the point the pipeline was freezing on me earlier on.. No clue, maybe some of the modules didn't load or something.
Apologies for the false alarm.
Cheers.

**Comment by leepc12** [comment]
No problem.

Please reopen this issue if the bug still persists.
