### ISSUE TITLE
Python egg cache directory error

### ISSUE THREAD

**Issue by jet456** [kundajelab/atac_dnase_pipelines#40]
Hi!

I am trying to run the pipeline and keep getting this error. I have tried:
export PYTHON_EGG_CACHE="/home/jet456/Pipeline/pythoneggcache"
chmod -R 777 /home/jet456/Pipeline/pythoneggcache

I also tried removing and recreating that directory.

```

	Script file        : '/home/jet456/Pipeline/atac.bds.20170310_101517_340/task.callpeak_macs2.macs2_atac_rep2.line_197.id_13.sh'
	Exit status        : '1'
	StdErr (10 lines)  :
		  [Errno 17] File exists: '/home/jet456/Pipeline/pythoneggcache/MACS2-2.1.0.20150731-py2.7-linux-x86_64.egg-tmp/MACS2'
		
		The Python egg cache directory is currently set to:
		
		  /home/jet456/Pipeline/pythoneggcache
		
		Perhaps your account does not have write access to this directory?  You can
		change the cache directory by setting the PYTHON_EGG_CACHE environment
		variable to point to an accessible directory.

Fatal error: /install/atac_dnase_pipeline-1.0.0/atac_dnase_pipelines/atac.bds, line 993, pos 2. Task/s failed.
atac.bds, line 70 :	main()
atac.bds, line 73 :	void main() { // atac pipeline starts here
atac.bds, line 85 :		call_peaks()
atac.bds, line 857 :	void call_peaks() { // for pooling two replicates and calling peaks on them
atac.bds, line 993 :		wait
```

**Comment by leepc12** [comment]
http://stackoverflow.com/a/2192369

Did you add that export line to ~/.bashrc or ~/.bash_profile? Can you try
with export PYTHON_EGG_CACHE="/tmp"?

Jin

**Comment by jet456** [comment]
Hi Jin,

Thanks for the quick response! I just tried adding it to my .bashrc and .bash_profile both and the pipeline crashed again. I had also tried setting PYTHON_EGG_CACHE to /tmp, but that didn't work either. 

Here is an abridged version of the other commands I ran.


```
export TMPDIR="/home/jet456/Pipeline/ATACTMP"

export _JAVA_OPTIONS="-Xms256M -Xmx728M -XX:ParallelGCThreads=1 -Djava.io.tmpdir=/home/jet456/Pipeline/ATACJAVATMP"

bds /path/to/atac.bds -species hg19 -nth 4 -se -bam1 /path/to/file1.fastqAligned.out.bam -bam2 /path/to/file2.fastqAligned.out.bam

```

Thanks!

**Comment by leepc12** [comment]
Did you install dependencies including MACS2 with install_dependencies.sh?

Jin

**Comment by jet456** [comment]
Hi Jin,

Yes, I ran the install_dependencies.sh script.

Thanks-

**Comment by jet456** [comment]
I'll double-check that MACS2 is installed.

**Comment by leepc12** [comment]
Check if other MACS2 binary is PREPENDED in your $PATH.

echo $PATH

The pipeline is designed to work with Conda-installed MACS2
(/your_conda_dir/envs/bds_atac/bin/macs2.

source activate bds_atac
which macs2
source deactivate

Jin

**Comment by jet456** [comment]
Hi Jin,

I tried that (cd /path/to/miniconda3/envs/bds_atac/bin, source activate), which didn't load macs2 into my PATH, so I used

export PATH="/path/to/bds_atac/bin:$PATH"

"which macs2" returned the correct location. I am rerunning the pipeline now and will let you know if it completes.

Thanks-

**Comment by jet456** [comment]
Hi Jin,

The pipeline got a bit further this time. Here is the current error.

```
Task failed:
	Program & line     : '/install/atac_dnase_pipeline-1.0.0/atac_dnase_pipelines/modules/callpeak_macs2.bds', line 197
	Task Name          : 'macs2_atac rep1'
	Task ID            : 'atac.bds.20170310_130225_033/task.callpeak_macs2.macs2_atac_rep1.line_197.id_10'
	Task PID           : '21139'
	Task hint          : 'if [[ -f $(which conda) && $(conda env list | grep bds_atac | wc -l) != "0" ]]; then source activate bds_atac; sleep 5; fi;  export PATH=/install/atac_dna'
	Task resources     : 'cpus: -1	mem: -1.0 B	wall-timeout: 8640000'
	State              : 'ERROR'
	Dependency state   : 'ERROR'
	Retries available  : '1'
	Input files        : '[/home/jet456/Pipeline/out/align/rep1/SRR1448792_1.fastqAligned.out.nodup.tn5.tagAlign.gz]'
	Output files       : '[/home/jet456/Pipeline/out/peak/macs2/rep1/SRR1448792_1.fastqAligned.out.nodup.tn5.pf.narrowPeak.gz, /home/jet456//Pipeline/out/peak/macs2/rep1/SRR1448792_1.fastqAligned.out.nodup.tn5.pf.gappedPeak.gz, /home/jet456/Pipeline/out/signal/macs2/rep1/SRR1448792_1.fastqAligned.out.nodup.tn5.pf.fc.signal.bigwig, /home/jet456/Pipeline/out/signal/macs2/rep1/SRR1448792_1.fastqAligned.out.nodup.tn5.pf.pval.signal.bigwig]'
	Script file        : '/home/jet456/Pipeline/atac.bds.20170310_130225_033/task.callpeak_macs2.macs2_atac_rep1.line_197.id_10.sh'
	Exit status        : '1'
	StdErr (10 lines)  :
		INFO  @ Fri, 10 Mar 2017 13:18:26: #4 Write summits bed file... /home/jet456/Pipeline/out/peak/macs2/rep1/SRR1448792_1.fastqAligned.out.nodup.tn5.pf_summits.bed 
		INFO  @ Fri, 10 Mar 2017 13:18:28: Done! 
		INFO  @ Fri, 10 Mar 2017 13:18:39: Read and build treatment bedGraph... 
		INFO  @ Fri, 10 Mar 2017 13:19:54: Read and build control bedGraph... 
		INFO  @ Fri, 10 Mar 2017 13:20:36: Build scoreTrackII... 
		INFO  @ Fri, 10 Mar 2017 13:21:13: Calculate scores comparing treatment and control by 'FE'... 
		INFO  @ Fri, 10 Mar 2017 13:28:22: Write bedGraph of scores... 
		INFO  @ Fri, 10 Mar 2017 13:31:45: Finished 'FE'! Please check '/home/jet456/Pipeline/out/peak/macs2/rep1/SRR1448792_1.fastqAligned.out.nodup.tn5.pf_FE.bdg'! 
		Chromosome GL000219.1 isn't in /install/atac_dnase_pipeline-1.0.0/GenomeData/hg19/hg19.chrom.sizes line 1 of stdin
```

**Comment by leepc12** [comment]
If `source activate bds_atac` didn't load MACS2 to your $PATH, you didn't install dependencies correctly. Please check if you have a correct `export` line for conda.

If you don't start from fastqs, you need use a different chromosome sizes file corresponding to the reference sequence `.fa` file that is used for mapping fastqs to bams.

Please find the exact reference sequence `.fa` used for mapping fastqs and generate chromosome sizes file with the following command:
```
faidx -x [REF_SEQ_FA_FILE]
cut -f1,2 [REF_SEQ_FA_FILE].fai >[NEW_CHR_SZ_FILE]
```

Or just fetch it by using USCS tool `fetchChromSizes`. 

With a new chr size file, add `-chrsz [NEW_CHR_SZ_FILE]` to the pipeline command line.

**Comment by jet456** [comment]
Hi Jin,

Apologies for the late response. To install dependencies, I ran ./install_dependencies.sh. That ran successfully. 

I will try running it with the fastqs. 

Thanks-

**Comment by jet456** [comment]
Hi Jin,

This error is fixed. I removed and reinstalled the pipeline after "git pull".
