### ISSUE TITLE
Add option to specify customized $TMP directory

### ISSUE THREAD

**Issue by fuxialexander** [kundajelab/atac_dnase_pipelines#42]
Great thanks for this well built pipeline first :)
I ran this pipeline on a hpc with a 10GB /tmp partition and it fails at 3 steps: sambamba sort, sort and something related to Picard (dedup and sort). After investigating, the main reason is /tmp is out of space during sorting large files. It would be good to be able to specify another tmp directory, e.g. "sort -T /another/tmp". And it can be added to env configuration file.

**Comment by leepc12** [comment]
`sort` uses `$TMPDIR` as a temporary directory. Please add the following lines to your ~/.bashrc or ~/.bash_profile.
```
export TMPDIR=/another/tmp
export TMP=/another/tmp
```

**Comment by fuxialexander** [comment]
@leepc12 Ahhh silly me... Previously not sure whether the shell setting can be picked up by those three tools. Thanks a million!
