### ISSUE TITLE
slurm partition, result names and fatal error

### ISSUE THREAD

**Issue by JensKeilwagen** [kundajelab/atac_dnase_pipelines#43]
Hi kundajelab,

Thanks again for providing and updating the pipeline. I'm using the following version:

Latest git commit: 3f3eeefd9763a1e00ac81a2244cf17adac5c64a4 (Sun Feb 26 14:12:05 2017)

and command lines as proposed:

bds_scr ENCSRXXX atac.bds -use_system slurm -species hg19 -nth 2 -type dnase-seq -subsample 50M -se -title ENCSRXXX ...

However, I observed the following problems:
- parameter -q does not work: all our jobs have been submitted to the default slurm partition
- the results do not all have the correct names. We expected the result files to be named like the title. However, this was not true for bigwig and relaxed peaks.
- some of the runs died with fatal errors, e.g.:

"Fatal error: atac.bds, line 577, pos 4. Task/s failed.

Creating checkpoint file: Config or command line option disabled checkpoint file creation, nothing done.
Fatal error: atac.bds, line 372, pos 2. Task/s failed.

Creating checkpoint file: Config or command line option disabled checkpoint file creation, nothing done."

or 

"Fatal error: atac.bds, line 372, pos 2. Task/s failed.

Creating checkpoint file: Config or command line option disabled checkpoint file creation, nothing done."

We would be grateful for any recommendations.

best regards, Jens

**Comment by leepc12** [comment]
Hello Jens,

1) parameter -q for SLURM: fixed in commit 4362a59.
Please get the latest pipeline and then `cp ./utils/clusterGeneric/run.pl $HOME/.bds/clusterGeneric/`.

2) file naming:
Not all output files use `-title` as a prefix. Some files (idr peaks/plots/logs, HTML report and ENCODE/QC json) do, but most files keep their original prefixes.

3) fata errors:
Please post a full .log or HTML report for debugging.

Jin

**Comment by leepc12** [comment]
I looked into your logs. For both cases, the pipeline code coulnd't detect adapters for raw fastqs of replicate 1. Are these fastqs for replicate 1 already trimmed? For replicate 2, there was no problem.

I also updated the pipeline to pool more than 10 fastqs per replicate. The old pipeline couldn't pool more than 10 fastqs per replicate. Please get the latest pipeline.

**Comment by JensKeilwagen** [comment]
Hi Jin,

Thanks a lot for the fast reply. We used standard ENCODE data sets and checking the ENCODE site for the experiment I could not receive any information about trimming. But it states "Raw sequencing data". Hence, I would assume the reads are not trimmed yet.

I updated the pipeline. However, it still produces fatal errors (see private email).

How should I proceed?

Best regards, Jens

**Comment by akundaje** [comment]
I believe the Stam Encode DNASE Fastqs are already trimmed.

Daniel - Can you confirm.

Anshul

**Comment by vervacity** [comment]
Hi Jens,

Confirming with Anshul, the Stam ENCODE DNase FASTQs are already trimmed.

Daniel

**Comment by akundaje** [comment]
Yeah so basically you need to turn the trimming option off. Jin - let him
know how to do that.

Anshul

**Comment by JensKeilwagen** [comment]
Thanks a lot.
As far as I understand all ENCODE data sets from John Stamatoyannopoulos
lab are already trimmed, aren't they?

Best regards, Jens

2017-03-21 18:29 GMT+01:00 Anshul Kundaje <notifications@github.com>:

> Yeah so basically you need to turn the trimming option off. Jin - let him
> know how to do that.
>
> Anshul
>

**Comment by akundaje** [comment]
Yes correct. The pipeline has a flag that turns the automated trimming off.
You would just need to activate that. Jin can tell you what the flag is.

-Anshul.

**Comment by leepc12** [comment]
For ENCSR000ELE, no adapter was detected for rep1. But for rep2, an adaptor AGATCGGAAGAGC (Illumina sequencer) was detected. That's why the pipeline kept going for rep2.

So we cannot use a flag `-trimmed_fastq` (skip trimming fastqs for all replicates) parameter here.

I updated the pipeline code to selectively trim fastqs that have adapters detected. Please get the latest pipeline and try again.

**Comment by akundaje** [comment]
CS/Daniel - Is it possible the automatic adapter detection code may have a
false positive adapter detection call? Cuz the Stam FASTQs should all be
pre-trimmed. If this is not a false call, we should report to the DCC and
let them know the inconsistency.

-Anshul.

**Comment by leepc12** [comment]
https://github.com/kundajelab/atac_dnase_pipelines/blob/master/utils/detect_adapter.py

Anshul, the automatic adapter detection code (`detect_adapter.py`) just tries to find the following adapter strings in ungzipped raw fastq file.
```
adapters = {
    'Illumina': b'AGATCGGAAGAGC',
    'Nextera ': b'CTGTCTCTTATA',
    'smallRNA': b'TGGAATTCTCGG'
}
```

**Comment by akundaje** [comment]
What was the read length in the FASTQ that has the adapters in it.

-Anshul.

**Comment by leepc12** [comment]
It's 50.

**Comment by akundaje** [comment]
And is that the same length as the other FASTQ that was also trimmed?

-A

**Comment by leepc12** [comment]
Yes

**Comment by akundaje** [comment]
Is this a paired-end dataset?

-A

**Comment by leepc12** [comment]
No, it's SE one.

**Comment by akundaje** [comment]
Oh ok. So then its likely the one that had the adapter infact does have it.

-Anshul.

**Comment by akundaje** [comment]
I think your fix is the right one. i.e. perform adapter detection and
trimming for each FASTQ independently.

**Comment by JensKeilwagen** [comment]
Thanks a lot for the clarification.

Am 21.03.2017 21:45 schrieb "Anshul Kundaje" <notifications@github.com>:
