### ISSUE TITLE
Error with `true_rep` parameter

### ISSUE THREAD

**Issue by jenchien** [kundajelab/atac_dnase_pipelines#46]
Hi Kundajelab,

Thanks again for sharing and maintaining the pipeline. I have ran the pipeline successfully with both `true_rep` and `no_idr` once for our experiments. Now I would like to get the idr result so I reran the pipeline but take `no_idr` out and leave only the `true_rep` parameter (same output folder). The pipeline skipped the `do_align()`, finished `call_peaks()`, but encountered the following error during idr step:

>Fatal error: /osc-fs_home/chang-j/software/atac_dnase_pipelines/atac.bds, line 1277, pos 33. Map 'idr_pr' does not have key '1'.

Is this due to I run twice with different parameters? The full stdout is attached here. Thanks in advance!

[iMT_hg38.atac.bds.macs2.idr.teelog.txt](https://github.com/kundajelab/atac_dnase_pipelines/files/908052/iMT_hg38.atac.bds.macs2.idr.teelog.txt)

**Comment by leepc12** [comment]
It's fixed in 6241adf

**Comment by jenchien** [comment]
Thanks for the prompt response. I pulled and tried again. It passed the last error point and finished `do_idr()` , but seems encounter another similar error:

> Fatal error: /osc-fs_home/chang-j/software/atac_dnase_pipelines/atac.bds, line 1402, pos 65. Map 'idr_pr_png' does not have key '1'.

Full stdout is here. Thanks!
[iMT_hg38.atac.bds.macs2.idr.bugfix.teelog.txt](https://github.com/kundajelab/atac_dnase_pipelines/files/908382/iMT_hg38.atac.bds.macs2.idr.bugfix.teelog.txt)

**Comment by leepc12** [comment]
fixed in 3a48fa6. please pull and try again.

**Comment by jenchien** [comment]
Another similar issue:

> Fatal error: /osc-fs_home/chang-j/software/atac_dnase_pipelines/modules/ENCODE_accession.bds, line 195, pos 19. Map 'map' does not have key 'N1'.

Thanks a lot.

**Comment by leepc12** [comment]
I am sorry bothering you so many times about this issue. It's finally fixed and tested in the commit a5d3efa.

**Comment by jenchien** [comment]
The latest commit works for me now. Thanks a lot for your patient in fixing the bug.
