### ISSUE TITLE
mention that TMPDIR must be set

### ISSUE THREAD

**Issue by antonkratz** [kundajelab/atac_dnase_pipelines#55]
Sugggestion, the installation instructions should mention that the shell variable `TMPDIR` must be set (I am not sure to where, I just set it to `/tmp` in my `.bashrc` and it seems to work). If it is not set - and by default it is not set in some fresh installations of Ubuntu/CentOS - the pipeline will crash. I think this is related to commit a6f7fabd4d36bfb200a3d9510ffd3d3cec548f21.

**Comment by leepc12** [comment]
Thanks for reporting this. It's fixed in 02f55b5.
If $TEMPDIR is not set, the pipeline will ignore it.
