### ISSUE TITLE
Bowtie dependency issue load

### ISSUE THREAD

**Issue by rbronste** [kundajelab/atac_dnase_pipelines#58]
Hi,

Trying to run on a single replicate of PE data and getting the following error, wondering if during Bioconda Bowtie dependency install the indexes are not created? 

== checking atac parameters ...
00:00:00.605	Error (modules/align_bowtie2.bds, line 38, pos 3): Bowtie2 index (-bwt2_idx) doesn't exists! (file: .1.bt2 or .1.bt2l)

Thanks.

Rob.

**Comment by leepc12** [comment]
Did you install genome database too (install_genome_database.sh)?

Jin

**Comment by rbronste** [comment]
Yes I did and it worked fine, all of the files are present.

**Comment by leepc12** [comment]
Did you specify species correctly? (e.g. `-species hg38`).

Can you post here your full command line and contents of default.env in the
repo directory?

Jin

**Comment by rbronste** [comment]
Sorry just figured it out, thought the Bowtie2 install under condo would automatically take the mm10_no_alt_analysis_set_ENCODE.fasta file to make an index, doing it myself currently with Bowtie2-build.

**Comment by leepc12** [comment]
Conda has nothing to do with bowtie2 index, index is built in
`install_genome_database.sh` and the installer does not automatically take
mm10. Please use the installer. If you didn't make genome database with
`install_genome_database.sh [SPECIES] [DEST_DIR]` then you will see another
error in downstream analysis.

If you want to use your own version of reference sequence for a specific
species, please take a look at  "Installer for genome data" in
https://kundajelab.github.io/bds_pipeline_modules/programming.html.

Jin

**Comment by rbronste** [comment]
Where are the index files (file: .1.bt2 or .1.bt2l) located once you use install_genome_database.sh? It created a number of files however I do not see those so not sure what path to use to link index to central command.

**Comment by leepc12** [comment]
I think you already specified the destination directory for all genome
database when you ran `install_genome_database.sh [SPECIES] [DEST_DIR]`.
Please take a look at `[DEST_DIR]`.
Or you can find it in `default.env` at the bottom.

Bowtie2 indices should be in `[DEST_DIR]/[SPECIES]/bwt2_idx/`.

Jin
