### ISSUE TITLE
ValueError: could not convert string to float: All

### ISSUE THREAD

**Issue by jet456** [kundajelab/atac_dnase_pipelines#59]
Hi!

We are trying to run the pipeline and are getting this error. I'm unsure if it's a bug in the pipeline or something wrong with our code. Running CentOS 6.8. Here is the output of our most recent run.

18609 /applications/atac_dnase_pipeline-1.0.0/atac_dnase_pipelines/ataqc/run_ataqc.py:915: FutureWarning: sort(columns=....      ) is deprecated, use sort_values(by=.....)
18610   sorted_results = merged.sort('corr', ascending=True)
18611 Traceback (most recent call last):
18612   File "/applications/atac_dnase_pipeline-1.0.0/atac_dnase_pipelines/ataqc/run_ataqc.py", line 1596, in <module>
18613     main()
18614   File "/applications/atac_dnase_pipeline-1.0.0/atac_dnase_pipelines/ataqc/run_ataqc.py", line 1545, in main
18615     ('gc_bias', plot_gc(gc_out)),
18616   File "/applications/atac_dnase_pipeline-1.0.0/atac_dnase_pipelines/ataqc/run_ataqc.py", line 213, in plot_gc
18617     data = np.loadtxt(fp, skiprows=1)
18618   File "/applications/miniconda3-4.3.11/miniconda3/envs/bds_atac/lib/python2.7/site-packages/numpy/lib/npyio.py", lin      e 928, in loadtxt
18619     items = [conv(val) for (conv, val) in zip(converters, vals)]
18620   File "/applications/miniconda3-4.3.11/miniconda3/envs/bds_atac/lib/python2.7/site-packages/numpy/lib/npyio.py", lin      e 659, in floatconv
18621     return float(x)
18622 ValueError: could not convert string to float: All
18623 Task failed:
18624         Program & line     : '/applications/atac_dnase_pipeline-1.0.0/atac_dnase_pipelines/modules/ataqc.bds', line 1      12
18625         Task Name          : 'ataqc rep4'
18626         Task ID            : 'atac.bds.20170713_124205_550_parallel_340/task.ataqc.ataqc_rep4.line_112.id_237'
18627         Task PID           : '32474'
18628         Task hint          : 'if [[ -f $(which conda) && $(conda env list | grep bds_atac | wc -l) != "0" ]]; then source activate bds_atac; sleep 5; fi;  export PATH=/applications/atac_dna'
18629         Task resources     : 'cpus: -1  mem: -1.0 B     wall-timeout: 8640000'
18630         State              : 'ERROR'
18631         Dependency state   : 'ERROR'
18632         Retries available  : '1'

**Comment by vervacity** [comment]
Hi!

It looks like it might be something to do with the Picard version you're using - if you have the outputs, if the `qc` folder still exists could you look there for a file that ends in `*_gc.txt` and share the file (or the top part of the file) with us? Otherwise, could you go ahead and run

Thanks for using the pipeline!

**Comment by jet456** [comment]
Hi! Thanks for the quick response!

In the qc directory there are 5 subdirectories, rep1 rep2 rep3 rep4 and rep5. They look the same, except for dates/times. Here is the first part of rep5/LIB026688_GEN00089321_S5_R1.trim.PE2SE_gc.txt:

```
## htsjdk.samtools.metrics.StringHeader
# picard.analysis.CollectGcBiasMetrics CHART_OUTPUT=/project00/studies/ExternalCellLines/analyses/FC_02923/july132017/qc/rep5/LIB026688_GEN00089321_S5_R1.trim.PE2SE_gcPlot.pdf SUMMARY_OUTPUT=/project00/studies/ExternalCellLines/analyses/FC_02923/july132017/qc/rep5/LIB026688_GEN00089321_S5_R1.trim.PE2SE_gcSummary.txt INPUT=/project00/studies/ExternalCellLines/analyses/FC_02923/july132017/align/rep5/LIB026688_GEN00089321_S5_R1.trim.PE2SE.nodup.bam OUTPUT=/project00/studies/ExternalCellLines/analyses/FC_02923/july132017/qc/rep5/LIB026688_GEN00089321_S5_R1.trim.PE2SE_gc.txt ASSUME_SORTED=false VERBOSITY=ERROR QUIET=true REFERENCE_SEQUENCE=/applications/atac_dnase_pipeline-1.0.0/GenomeData/hg19/male.hg19.fa    SCAN_WINDOW_SIZE=100 MINIMUM_GENOME_FRACTION=1.0E-5 IS_BISULFITE_SEQUENCED=false METRIC_ACCUMULATION_LEVEL=[ALL_READS] ALSO_IGNORE_DUPLICATES=false STOP_AFTER=0 VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
## htsjdk.samtools.metrics.StringHeader
# Started on: Fri Jul 14 20:21:16 EDT 2017

## METRICS CLASS	picard.analysis.GcBiasDetailMetrics
ACCUMULATION_LEVEL	READS_USED	GC	WINDOWS	READ_STARTS	MEAN_BASE_QUALITY	NORMALIZED_COVERAGE	ERROR_BAR_WIDTH	SAMPLE	LIBRARY	READ_GROUP
All Reads	ALL	0	132617	848	33	0.496927	0.017065			
All Reads	ALL	1	94890	1	0	0.000819	0.000819			
All Reads	ALL	2	109162	2	0	0.001424	0.001007
```

Thanks--

**Comment by vervacity** [comment]
Hi!

Great, that was exactly what I needed to see. Looks like you're using a different version of Picard in which the columns are not what they used to be. I'll have a fix for it probably by early next week, but in the meantime you could adjust your Picard version to be the one listed in `requirements.txt`. You could also actually just continue on, since this error is only in the QC checks - if your data looks good then you should be fine to continue with your analyses. But we will fix it, so I'll get back to you once we've pushed a fix and you are welcome to wait until then.

**Comment by jet456** [comment]
Hi!

Thanks again for the quick response. We can wait until next week -- would you mind letting me know when it's ready?

Thanks--

**Comment by vervacity** [comment]
Absolutely - we'll make a note here, confirm it works, and close the issue.

**Comment by jet456** [comment]
Thank you so much!

**Comment by jet456** [comment]
Hi!

Wondering what the status is on this?

Thanks-

**Comment by vervacity** [comment]
Hi! Sorry for the delay, and thanks for the reminder - the fix is in, so if you go ahead and pull the latest version of the pipeline, `ataqc` should be updated to work with different versions of Picard outputs. Thanks!

**Comment by jet456** [comment]
Thanks so much! We'll try it out later today.
