### ISSUE TITLE
Error and no QC following 3 replicate PE run

### ISSUE THREAD

**Issue by rbronste** [kundajelab/atac_dnase_pipelines#62]
Hi Jin,

Quick question, ran the pipeline in the following way and got the following error after each replicate stage (3 PE replicates) finished, and wound up with no QC or Macs peaks but most of the other output as far as I can tell:

`bds atac.bds -species mm10 -nth 16 -mapq_thresh 20 -no_dup_removal -chrsz /sonas-hs/tollkuhn/hpc_norepl/home/rbronste/mm10.chrom.sizes -gensz mm`

```
Gpr.reader(565):	File not found '/mnt/grid/tollkuhn/hpc_norepl/home/data/rbronste/atac_dnase_pipelines/out/qc/rep1/298765_S1_R1_001_dedup.trim.PE2SE.nodup.pbc.qc'
Fatal error: modules/log_parser.bds, line 244, pos 34. Trying to access element number 0 from list 'arr' (list size: 0).

Creating checkpoint file: Config or command line option disabled checkpoint file creation, nothing done.
Fatal error: modules/ENCODE_accession.bds, line 184, pos 25. Map 'map_pbc' does not have key 'PBC1'.

Creating checkpoint file: Config or command line option disabled checkpoint file creation, nothing done.
Fatal error: atac.bds, line 385, pos 2. Task/s failed.

Creating checkpoint file: Config or command line option disabled checkpoint file creation, nothing done.
```

Thanks!

Rob.

**Comment by rbronste** [comment]
I just noticed I did not have the <bool> of 1 for -no_dup_removal, could that have been the cause?

**Comment by leepc12** [comment]
No, -no_dup_removal 1 should work correctly, but it's a flag so I recommend not to add 1.

I think I fixed it in the commit 1bef188. Please try with the latest pipeline.

**Comment by rbronste** [comment]
You fixed the reason for that error above?

**Comment by leepc12** [comment]
Yes, I pushed that commit an hour ago..
