### ISSUE TITLE
500K narrowPeak vs Conservative set

### ISSUE THREAD

**Issue by rbronste** [kundajelab/atac_dnase_pipelines#67]
More of a general question, trying to use some peak sets with DiffBind to call differential peaks and wondering about which to use, not sure what the Rep1-2 peak set under conservative means, a combination of those biological replicates? So far using the 500K FDR .1 narrowPeak files. Thanks.

**Comment by leepc12** [comment]
Rep1-2 peak set under conservative directory (`peak/macs2/idr/conservative_set/`) are IDR peaks from true replicate 1, 2 and pooled replicates. We don't recommend to use IDR peaks unless your samples are very deep. Please use *.500K.pval0.01.naive_overlap.filt.narrowPeak.gz` in `peak/macs2/overlap/`.
