### ISSUE TITLE
No adapter trimming?

### ISSUE THREAD

**Issue by PocketChangeJ** [kundajelab/atac_dnase_pipelines#74]
Hi guys, 
I've just updated the pipeline and testing on one of my previously analyzed samples to be sure all works ok - noticed my adapters are not getting trimmed...
`== checking adapters to be trimmed ...
Rep1 R1 adapters (PE) : 
        00: no adapter specified.
Rep1 R2 adapters (PE) : 
        00: no adapter specified.
Rep2 R1 adapters (PE) : 
        00: no adapter specified.
Rep2 R2 adapters (PE) : 
        00: no adapter specified.`

The pipeline just proceeds to straight to bowtie mapping..
Thank you!

**Comment by leepc12** [comment]
There was an announcement about this in the google group discussion channel
a few weeks ago.

https://groups.google.com/forum/#!topic/klab_genomic_pipelines_discuss/NQ8cZdQZMo8

Please use -auto_detect_adapter.

Thanks,

Jin

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#m_-3510697599444994146_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by PocketChangeJ** [comment]
Oh! Great, thank you! Guess need to catch up on the reading.
Thanks again!
