### ISSUE TITLE
cp --remove-destination does not work on OS

### ISSUE THREAD

**Issue by elhamazizi** [kundajelab/atac_dnase_pipelines#79]
Error when running install_genome_data.sh on OS:

Extracting/processing data files...
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory

**Comment by leepc12** [comment]
Please follow the instruction I sent you via email and let us know if it works. Then we will make a hotfix for Mac OS.

**Comment by siyunw** [comment]
I also have a error when running bash install_genome_data.sh hg19 datadir

AttributeError: module 'enum' has no attribute 'IntFlag'

Do you know how i could avoid this error?

**Comment by leepc12** [comment]
@siyunw Can you post a full error log here? Which OS did you use?

**Comment by siyunw** [comment]
this time the error is 
"tar: Child returned status 1
tar: Error is not recoverable: exiting now"

Here is the full log:
This script installs data for genome [GENOME] on a directory [DATA_DIR].
Genome data files will be installed on [DATA_DIR]/[GENOME].
A species file [DATA_DIR]/bds_atac_species.conf will be generated and added to default.conf.

Supported genomes: hg19, mm9, hg38 and mm10

Usage: ./install_genome_data.sh [GENOME] [DATA_DIR]
  Example: ./install_genome_data.sh hg19 /genome_data

[slwang]:$ bash install_genome_data.sh hg19 data_dir_hg19


Downloading files...
--2017-11-02 16:15:56--  http://mitra.stanford.edu/kundaje/genome_data/hg19/globalmap_k20tok54.tgz
Resolving mitra.stanford.edu... 171.65.76.236
Connecting to mitra.stanford.edu|171.65.76.236|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 249559554 (238M) [application/x-gzip]
Saving to: “globalmap_k20tok54.tgz”

100%[======================================================================================>] 249,559,554 49.6M/s   in 5.0s    

2017-11-02 16:16:03 (47.9 MB/s) - “globalmap_k20tok54.tgz” saved [249559554/249559554]

--2017-11-02 16:16:03--  http://hgdownload.cse.ucsc.edu/goldenpath/hg19/encodeDCC/referenceSequences/male.hg19.fa.gz
Resolving hgdownload.cse.ucsc.edu... 128.114.119.163
Connecting to hgdownload.cse.ucsc.edu|128.114.119.163|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 936272240 (893M) [application/x-gzip]
Saving to: “male.hg19.fa.gz”

100%[======================================================================================>] 936,272,240 37.6M/s   in 22s     

2017-11-02 16:16:26 (40.7 MB/s) - “male.hg19.fa.gz” saved [936272240/936272240]

--2017-11-02 16:16:36--  http://hgdownload.cse.ucsc.edu/goldenpath/hg19/encodeDCC/wgEncodeMapability/wgEncodeDacMapabilityConsensusExcludable.bed.gz
Resolving hgdownload.cse.ucsc.edu... 128.114.119.163
Connecting to hgdownload.cse.ucsc.edu|128.114.119.163|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4731 (4.6K) [application/x-gzip]
Saving to: “wgEncodeDacMapabilityConsensusExcludable.bed.gz”

100%[======================================================================================>] 4,731       --.-K/s   in 0s      

2017-11-02 16:16:37 (221 MB/s) - “wgEncodeDacMapabilityConsensusExcludable.bed.gz” saved [4731/4731]

--2017-11-02 16:16:37--  http://mitra.stanford.edu/kundaje/genome_data/hg19/ataqc/hg19_gencode_tss_unique.bed.gz
Resolving mitra.stanford.edu... 171.65.76.236
Connecting to mitra.stanford.edu|171.65.76.236|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 235292 (230K) [application/x-gzip]
Saving to: “hg19_gencode_tss_unique.bed.gz”

100%[======================================================================================>] 235,292     --.-K/s   in 0.1s    

2017-11-02 16:16:37 (2.27 MB/s) - “hg19_gencode_tss_unique.bed.gz” saved [235292/235292]

--2017-11-02 16:16:37--  http://mitra.stanford.edu/kundaje/genome_data/hg19/ataqc/reg2map_honeybadger2_dnase_all_p10_ucsc.bed.gz
Resolving mitra.stanford.edu... 171.65.76.236
Connecting to mitra.stanford.edu|171.65.76.236|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11219795 (11M) [application/x-gzip]
Saving to: “reg2map_honeybadger2_dnase_all_p10_ucsc.bed.gz”

100%[======================================================================================>] 11,219,795  23.4M/s   in 0.5s    

2017-11-02 16:16:38 (23.4 MB/s) - “reg2map_honeybadger2_dnase_all_p10_ucsc.bed.gz” saved [11219795/11219795]

--2017-11-02 16:16:38--  http://mitra.stanford.edu/kundaje/genome_data/hg19/ataqc/reg2map_honeybadger2_dnase_prom_p2.bed.gz
Resolving mitra.stanford.edu... 171.65.76.236
Connecting to mitra.stanford.edu|171.65.76.236|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 666590 (651K) [application/x-gzip]
Saving to: “reg2map_honeybadger2_dnase_prom_p2.bed.gz”

100%[======================================================================================>] 666,590     3.67M/s   in 0.2s    

2017-11-02 16:16:38 (3.67 MB/s) - “reg2map_honeybadger2_dnase_prom_p2.bed.gz” saved [666590/666590]

--2017-11-02 16:16:38--  http://mitra.stanford.edu/kundaje/genome_data/hg19/ataqc/reg2map_honeybadger2_dnase_enh_p2.bed.gz
Resolving mitra.stanford.edu... 171.65.76.236
Connecting to mitra.stanford.edu|171.65.76.236|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18386700 (18M) [application/x-gzip]
Saving to: “reg2map_honeybadger2_dnase_enh_p2.bed.gz”

100%[======================================================================================>] 18,386,700  25.9M/s   in 0.7s    

2017-11-02 16:16:39 (25.9 MB/s) - “reg2map_honeybadger2_dnase_enh_p2.bed.gz” saved [18386700/18386700]

--2017-11-02 16:16:39--  http://mitra.stanford.edu/kundaje/genome_data/hg19/ataqc/dnase_avgs_reg2map_p10_merged_named.pvals.gz
Resolving mitra.stanford.edu... 171.65.76.236
Connecting to mitra.stanford.edu|171.65.76.236|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 154254597 (147M) [application/x-gzip]
Saving to: “dnase_avgs_reg2map_p10_merged_named.pvals.gz”

100%[======================================================================================>] 154,254,597 50.4M/s   in 2.9s    

2017-11-02 16:16:43 (50.4 MB/s) - “dnase_avgs_reg2map_p10_merged_named.pvals.gz” saved [154254597/154254597]

--2017-11-02 16:16:43--  http://mitra.stanford.edu/kundaje/genome_data/hg19/ataqc/eid_to_mnemonic.txt
Resolving mitra.stanford.edu... 171.65.76.236
Connecting to mitra.stanford.edu|171.65.76.236|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2340 (2.3K) [text/plain]
Saving to: “eid_to_mnemonic.txt”

100%[======================================================================================>] 2,340       --.-K/s   in 0s      

2017-11-02 16:16:43 (181 MB/s) - “eid_to_mnemonic.txt” saved [2340/2340]


gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by leepc12** [comment]
@siyunw, I am working on a hot fix for this. tar error an cp error will be fixed.
BTW How did you fix `AttributeError: module 'enum' has no attribute 'IntFlag'` error?

**Comment by siyunw** [comment]
The module 'enum' has no attribute 'IntFlag' error was likely due to I have conflict versions of pythons. I log out and log in after re-installed the minoconda 3, then it showed the new error.

**Comment by leepc12** [comment]
Please get the the latest pipeline and try again.
