### ISSUE TITLE
Does the official BDS work now instead of the patched one?

### ISSUE THREAD

**Issue by ghuls** [kundajelab/atac_dnase_pipelines#88]
In the manual:

> Install BigDataScript v0.99999e (forked) on your system. The original BDS v0.99999e does not work correctly with the pipeline (see PR #142 and issue #131).

When following the PR, it seems that the problem should have been fixed in recent versions of BDS.

**Comment by leepc12** [comment]
No, Issue 131 still persists in the latest official BDS.
