### ISSUE TITLE
Install error during IDR replacement section of install_dependencies.sh: unable to execute 'gcc'

### ISSUE THREAD

**Issue by AmandaBirmingham** [kundajelab/atac_dnase_pipelines#90]
When attempting to install the pipeline on a new, fresh linux instance from Amazon Web Services (I have tried on both Amazon Linux 2017.09.1 and Ubuntu 16.04 instances), I encounter a fatal error while running install_dependencies.sh.  The error occurs during the section of the install script that uninstalls IDR 2.0.3 and installs the latest one; I think it occurs during the 'python3 setup.py install' call.  Here are the messages I receive:

gcc -pthread -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ubuntu/miniconda3/envs/bds_atac_py3/lib/python3.5/site-packages/numpy/core/include -I/home/ubuntu/miniconda3/envs/bds_atac_py3/include/python3.5m -c idr/inv_cdf.c -o build/temp.linux-x86_64-3.5/idr/inv_cdf.o
unable to execute 'gcc': No such file or directory
error: command 'gcc' failed with exit status 1

As you can see, the conda environment appears to be failing to find a gcc compiler.  Perhaps this is related to a reported conda issue (https://github.com/conda/conda/issues/6030 ) but this issue appears to have been fixed in the conda version that the install is using (running conda -V gives me 'conda 4.4.7').

Below are the commands that I ran on a fresh Ubuntu 16.04 instance from AWS that reproduce this error:
sudo add-apt-repository ppa:webupd8team/java -y
sudo apt-get update
sudo apt-get install oracle-java8-installer
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh
[log out, log back in to re-source]
wget https://github.com/leepc12/BigDataScript/blob/master/distro/bds_Linux.tgz?raw=true -O bds_Linux.tgz
mv bds_Linux.tgz $HOME && cd $HOME && tar zxvf bds_Linux.tgz
[get msg: mv: 'bds_Linux.tgz' and '/home/ubuntu/bds_Linux.tgz' are the same file]
nano $HOME/.bashrc
[add export PATH=$PATH:$HOME/.bds to end of bashrc, then write out and exit nano]
[log out, log back in to re-source]
git clone https://github.com/kundajelab/atac_dnase_pipelines --recursive
cd atac_dnase_pipelines [Note that this command is NOT in install instructions, but is necessary to get to the directory where the next command can be recognized]
bash install_dependencies.sh

Any help resolving this issue would be greatly appreciated!

**Comment by leepc12** [comment]
I am sorry for late response.

Can you try with Conda 4.4.3 too? You can find it on
https://repo.continuum.io/miniconda/
<https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh>.
That's the version I am using.

Also please make sure that you have gcc installed on your system. It's
weird why the very basic compiler like gcc doesn't exist on your system. I
also use Ubuntu 16.04 but gcc is pre-installed when OS is installed.

sudo apt-get install gcc gfortran

Thanks,

Jin

**Comment by leepc12** [comment]
closing this due to long inactivity
