### ISSUE TITLE
Bowtie2 error

### ISSUE THREAD

**Issue by MengjunWu** [kundajelab/atac_dnase_pipelines#91]
Hi, 
I got some errors when proceed to the mapping step. then I just use the bowtie2 command manually, It seems to have something to do with the --mm setting of bowtie2. 

In the pipeline, the parameters of bowtie2 is set as: bowtie2 -k $multimapping -X2000 --local --mm --threads...
Running this command line, I got some errors:
mmap: Invalid argument
Error: Could not memory-map the index file mypath/mm10/bowtie2_index/mm10_no_alt_analysis_set_ENCODE.fasta.rev.2.bt2

But if I remove --mm, it will work.

Any idea why is it? Can we change the bowtie parameter settings. I am using the Slurm clusters 

Many thanks in advance!

Best,
Mengjun

**Comment by leepc12** [comment]
Please update your pipeline code and use `-no_idx_on_mem_bwt2`. This removes `--mm` flag in the bowtie2 mapping command line.

**Comment by MengjunWu** [comment]
Many thanks, it works. 
But I have the problem that when I run BDS command directly on an interactive node, every time I close or log out of the interactive node,  the pipeline stops running  and the screen of the pipeline becomes dead. Do you know why this happening?  Thank you!
