### ISSUE TITLE
Please use "sort -k1,1 -k2,2n" with LC_COLLATE=C,  or bedSort and try again.

### ISSUE THREAD

**Issue by sky-peng** [kundajelab/atac_dnase_pipelines#93]
Hello
I met a problem when i run the pipelines as follows:
bds /home/ye/atac_dnase_pipelines/atac.bds -species hg19 -nth 10 -fastq1_1 ENCLB112FTD_R1.fastq.gz -fastq1_2 ENCLB112FTD_R2.fastq.gz -auto_detect_adapter
The error was like this:

/ngs/data/ATACseq/human/out/peak/macs2/rep1/ENCLB112FTD_R1.trim.PE2SE.nodup.tn5.pf.fc.signal.srt.bedgraph is not case-sensitive sorted at line 2.  Please use "sort -k1,1 -k2,2n" with LC_COLLATE=C,  or bedSort and try again.
Task failed:
        Program & line     : '/home/ye/atac_dnase_pipelines/modules/callpeak_macs2_atac.bds', line 74
        Task Name          : 'macs2 n/s rep1'
        Task ID            : 'atac.bds.20180302_125823_487/task.callpeak_macs2_atac.macs2_n_s_rep1.line_74.id_32'
        Task PID           : '14181'
        Task hint          : 'if [[ -f $(which conda) && $(conda env list | grep bds_atac | wc -l) != "0" ]]; then source activate bds_atac; sleep 5; fi;  export PATH=/home/ye/atac'
        Task resources     : 'cpus: -1  mem: -1.0 B     wall-timeout: 8640000'
        State              : 'ERROR'
        Dependency state   : 'ERROR'
        Retries available  : '1'
        Input files        : '[/ngs/data/ATACseq/human/out/align/rep1/ENCLB112FTD_R1.trim.PE2SE.nodup.tn5.tagAlign.gz]'
        Output files       : '[/ngs/data/ATACseq/human/out/peak/macs2/rep1/ENCLB112FTD_R1.trim.PE2SE.nodup.tn5.pf.pval0.01.300K.narrowPeak.gz, /ngs/data/ATACseq/human/out/signal/macs2/rep1/ENCLB112FTD_R1.trim.PE2SE.nodup.tn5.pf.fc.signal.bigwig, /ngs/data/ATACseq/human/out/signal/macs2/rep1/ENCLB112FTD_R1.trim.PE2SE.nodup.tn5.pf.pval.signal.bigwig]'
        Script file        : '/ngs/data/ATACseq/human/atac.bds.20180302_125823_487/task.callpeak_macs2_atac.macs2_n_s_rep1.line_74.id_32.sh'
        Exit status        : '1'
        StdErr (10 lines)  :
                INFO  @ Fri, 02 Mar 2018 15:04:18: #4 Write peak in narrowPeak format file... /ngs/data/ATACseq/human/out/peak/macs2/rep1/ENCLB112FTD_R1.trim.PE2SE.nodup.tn5.pf_peaks.narrowPeak
                INFO  @ Fri, 02 Mar 2018 15:04:21: #4 Write summits bed file... /ngs/data/ATACseq/human/out/peak/macs2/rep1/ENCLB112FTD_R1.trim.PE2SE.nodup.tn5.pf_summits.bed
                INFO  @ Fri, 02 Mar 2018 15:04:23: Done!
                INFO  @ Fri, 02 Mar 2018 15:04:31: Read and build treatment bedGraph...
                INFO  @ Fri, 02 Mar 2018 15:05:06: Read and build control bedGraph...
                INFO  @ Fri, 02 Mar 2018 15:05:23: Build scoreTrackII...
                INFO  @ Fri, 02 Mar 2018 15:05:38: Calculate scores comparing treatment and control by 'FE'...
                INFO  @ Fri, 02 Mar 2018 15:08:24: Write bedGraph of scores...
                INFO  @ Fri, 02 Mar 2018 15:10:03: Finished 'FE'! Please check '/ngs/data/ATACseq/human/out/peak/macs2/rep1/ENCLB112FTD_R1.trim.PE2SE.nodup.tn5.pf_FE.bdg'!
                /ngs/data/ATACseq/human/out/peak/macs2/rep1/ENCLB112FTD_R1.trim.PE2SE.nodup.tn5.pf.fc.signal.srt.bedgraph is not case-sensitive sorted at line 2.  Please use "sort -k1,1 -k2,2n" with LC_COLLATE=C,  or bedSort and try again.

Fatal error: /home/ye/atac_dnase_pipelines/atac.bds, line 1200, pos 2. Task/s failed.
atac.bds, line 82 :     main()
atac.bds, line 85 :     void main() { // atac pipeline starts here
atac.bds, line 97 :             call_peaks()
atac.bds, line 1018 :   void call_peaks() { // for pooling two replicates and calling peaks on them
atac.bds, line 1200 :           wait

What should i do to solve this error? Can you give me some suggestions?
Thanks a lot!

**Comment by boxiangliu** [comment]
Hello @leepc12, have you had a chance to look at this yet?

**Comment by leepc12** [comment]
It's weird. Pipeline already uses `sort -k1,1 -k2,2n` with `export LC_COLLATE=C`.
I changed the sorting command line a bit to directly specify LC_COLLATE.
Please update the pipeline and try again.

**Comment by boxiangliu** [comment]
Sorry for the delay. We will reinstall and let you know!

**Comment by leepc12** [comment]
closing this due to long inactivity
